manifest:
  reproduce:
    exe: false
modules:
  load:
  - access-test/pr56-1
  - something/2021.02.003
  use:
  - /g/data/vk83/modules
  - /g/data/vk83/software/modules
  - /g/data/vk83/prerelease/modules
name: a cool config
